Add mail
wolox-training/rr-rails pull request #14
Opened 2018-07-02 21:11 UTC by holywyvern

# Summary

- Added sidekiq as a gem
- Created a notification job
- Configure jobs to use sidekiq as it's queue
- Added the sending mechanism when an user rents a book
- Configured mail server options

# Trello Card

https://trello.com/c/3YgnxdQ8

2018-07-03 11:50 UTC, juanisierra requested changes

2018-07-03 11:50 UTC, juanisierra commented on .gitgnore
> +.env
This file is not correctly named so it won't work

2018-07-03 11:50 UTC, juanisierra commented on app/mailers/application_mailer.rb
> +  default from: ENV['no-reply@training.wolox.com.ar']
Why is the env variable named like a mail?

2018-07-03 11:50 UTC, juanisierra commented on config/application.rb
> +      domain: ENV['MAILER_DOMAIN'],
Try using rails secrets for this variables

2018-07-05 19:23 UTC, juanisierra requested changes

2018-07-05 19:23 UTC, juanisierra commented on .gitgnore
> +.env
Remove this file please

2018-07-05 19:23 UTC, juanisierra commented on config/secrets.yml
> +    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
You can create a default environment with all variables in common and then inherit it from the others

2018-07-05 19:23 UTC, juanisierra commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
Put it inside of the group defined below here so it's better organized

2018-07-06 13:54 UTC, leamotta submitted a review, later dismissed

2018-07-06 13:54 UTC, leamotta commented on app/controllers/api/v1/users/rents_controller.rb
> +          RentNotificationsJob.perform_later(rent)
It is better to just send the rent id here, that way you don't serialize the whole entity into redis, using potentially a lot of memory.

2018-07-06 13:54 UTC, leamotta commented on config/secrets.yml
> +    <<: *default
🤔  this file should already be created at the start of the project. You need to at least have the `secret_key_base` here
You can set it up like this

development:
&nbsp;  secret_key_base: xxxxxxx

test:
&nbsp;  secret_key_base: xxxxxxx

production:
&nbsp;  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

You can read about it here for example https://medium.com/@michaeljcoyne/understanding-the-secret-key-base-in-ruby-on-rails-ce2f6f9968a1

2018-07-10 12:55 UTC, juanisierra approved these changes

2018-07-10 13:27 UTC, merged